# Generated by Django 5.2.7 on 2025-11-05 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(db_index=True, max_length=255)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('weather_description', models.CharField(max_length=255)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('temperature_unit', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit'), ('K', 'Kelvin')], db_index=True, default='C', max_length=1)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_snapshots', to='cities_light.city')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('served_from_cache', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('weather_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='weather.weathersnapshot')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='weathersnapshot',
            index=models.Index(fields=['city_name', 'temperature_unit', '-fetched_at'], name='weather_wea_city_na_2640d1_idx'),
        ),
        migrations.AddIndex(
            model_name='weathersnapshot',
            index=models.Index(fields=['-fetched_at'], name='weather_wea_fetched_b4d8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherquery',
            index=models.Index(fields=['-timestamp'], name='weather_wea_timesta_00b479_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherquery',
            index=models.Index(fields=['ip_address', '-timestamp'], name='weather_wea_ip_addr_77615a_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherquery',
            index=models.Index(fields=['served_from_cache'], name='weather_wea_served__247fb3_idx'),
        ),
    ]
